fix: AttributeError in text_to_block_list
An AttributeError occurs because .strip() is called on a NoneType object.

Error message:
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/widgets/blocks/text.py", line 53, in process_content
    self.get_parent().add_content(current_text)
  File "/app/share/Alpaca/alpaca/widgets/message.py", line 168, in add_content
    for block in blocks.text_to_block_list(content):
  File "/app/share/Alpaca/alpaca/widgets/blocks/__init__.py", line 65, in text_to_block_list
    content = match.group('latex_content1').strip() or match.group('latex_content2').strip()
AttributeError: 'NoneType' object has no attribute 'strip'